# Generated by Django 5.2.7 on 2025-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
    ]
